name: Python Playwright Tests

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

env:
  standard_user_id: ${{ secrets.STANDARD_USER_ID }}
  general_pw: ${{ secrets.GENERAL_PW }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest -v --html=report.html --self-contained-html

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.html